export type { SlideType } from './types';
export { introSlides } from './intro';
export { llmSlides } from './llm';
export { fluencySlides } from './fluency';
export { promptingSlides } from './prompting';
export { modelsSlides } from './models';
export { copilotSlides } from './copilot';
export { copilotCliSlides } from './copilot-cli';
export { privacySlides } from './privacy';
export { securitySlides } from './security';
export { instructionsSlides } from './instructions';
export { contextSlides } from './context';
export { skillsSlides } from './skills';
export { repeatingSlides } from './repeating';
export { spacesSlides } from './spaces';
export { evolutionSlides } from './evolution';
export { multiagentSlides } from './multiagent';
export { mcpSlides } from './mcp';
