export type { SlideType } from './types';
export { introSlides } from './intro';
export { llmSlides } from './llm';
export { fluencySlides } from './fluency';
export { modelsSlides } from './models';
export { copilotSlides } from './copilot';
export { instructionsSlides } from './instructions';
export { contextSlides } from './context';
export { skillsSlides } from './skills';
export { repeatingSlides } from './repeating';
export { multiagentSlides } from './multiagent';
